project:
  type: website
  output-dir: docs
  


website:
  navbar:
    logo: "tabs/tools/images/dataidlogo.png"
    left:
      - text: 'Home'
        href: index.qmd

      - text: 'Units'
        menu:
          - tabs/units/biosids/biosids.qmd

      - text: 'Training Programmes'
        menu:
          - tabs/units/radiant/radiant.qmd

# Right bar content
    right:
      - tabs/about/about.qmd
      - text: 'Blog'
        href: tabs/blog/blog.qmd
      - text: 'Tools'
        href: tabs/tools/tools.qmd

  sidebar:
    - id: biosids
      title: BioSIDS
      collapse-level: 1
      align: left
      style: "docked"
      search: true
      contents:
        - text: Welcome to BioSIDS
          href: tabs/units/biosids/biosids.qmd
        - text: About BioSIDS
          href: tabs/units/biosids/about_biosids.qmd
          
    - id: training
      title: Training
      collapse-level: 1
      align: left
      style: "docked"
      search: true
      contents:
        - text: Welcome to RADIANT
          href: tabs/units/radiant/radiant.qmd
        - text: About RADIANT
          href: tabs/units/radiant/about_radiant.qmd

format: 
  html: 
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 300px
      gutter-width: 1.5rem
    theme: cosmo
    embed-resources: true
    self-contained: true
    page-layout: full
    fig-dpi: 300
    toc: true



