project:
  type: website
  output-dir: docs
  
title-block-banner: 'blue'
title-block-banner-color: '#FFA319FF'
title-block-categories: true
title-block-tags: true

website:
  navbar:
    logo: "tabs/tools/images/dataidlogo.png"
    left:
      - text: 'Home'
        href: index.qmd

      - text: 'Units'
        menu:
          - tabs/units/biosids/biosids.qmd

      - text: 'Training'
        menu:
          - tabs/units/radiant/radiant.qmd

# Right bar content
    right:
      - tabs/about/about.qmd
      - text: 'Blog'
        href: tabs/blog/blog.qmd
      - text: 'Tools'
        href: tabs/tools/tools.qmd

  sidebar:
    - id: biosids
      title: BioSIDS
      collapse-level: 1
      align: left
      style: "docked"
      search: true
      contents:
        - text: Welcome to BioSIDS
          href: tabs/units/biosids/biosids.qmd
        - text: About BioSIDS
          href: tabs/units/biosids/about_biosids.qmd
          
    - id: training
      title: Training
      collapse-level: 1
      align: left
      style: "docked"
      search: true
      contents:
        - text: Welcome to RADIANT
          href: tabs/units/radiant/radiant.qmd
        - text: About RADIANT
          href: tabs/units/radiant/about_radiant.qmd

  #Footer-----------------------------------------------------------------------       
  page-footer:
    left: "© DATAAID CONSULTANTS 2025"
    center: "[About](tabs/about/about.qmd)"
    right: "Built with [Quarto](https://quarto.org/)"

#Format-------------------------------------------------------------------------     
format:
  html: 
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    theme:
      light: flatly
      dark: [latly, theme-dark.scss]
    embed-resources: true
    self-contained: true
    page-layout: full
    fig-dpi: 300
    toc: true

editor: visual



